In [80]:
import pandas as pd

In [129]:

lang_df = pd.read_csv("vegetableLanguage.csv", index_col=0)

min_df_transposed = df_min.T
max_df_transposed = df_max.T
avg_df_transposed = df_avg.T

lang_df.set_index('English', inplace=True)
lang_df_reordered = lang_df.loc[min_df_transposed.index]
combined_df = pd.concat([lang_df_reordered, min_df_transposed, max_df_transposed, avg_df_transposed], axis=1)
combined_df.columns = ['Nepali', 'Min Price', 'Max Price', 'Avg Price']
combined_df.to_csv("today_prices.csv")

In [133]:
combined_df

,Nepali,Min Price,Max Price,Avg Price
Tomato Big(Indian) (KG),गोलभेडा ठूलो(भारतीय) (केजी),35,40,37.67
Tomato Small(Local) (KG),गोलभेडा सानो(लोकल) (के.जी.),30,35,32.67
Tomato Small(Tunnel) (KG),गोलभेडा सानो(टनेल) (के जी),32,42,36.00
Tomato Small(Indian) (KG),गोलभेडा सानो(भारतीय) (के जी),30,35,32.67
Potato Red (KG),आलु रातो (के.जी.),60,65,62.33
...,...,...,...,...
Fish Fresh(Rahu) (KG),ताजा माछा(रहु) (के जी),370,380,375.00
Fish Fresh(Bachuwa) (KG),ताजा माछा(बचुवा) (के जी),270,280,275.00
Fish Fresh(Chhadi) (KG),ताजा माछा(छडी) (के जी),240,260,250.00
Fish Fresh(Mungari) (KG),ताजा माछा(मुंगरी) (के जी),250,270,260.00
Tree Tomato (Kg),रुख टमाटर (केजी),120,150,133.33